var WebServer = require('../config/WebServer');

var Share_Prog = {
   Sample_Sheet_Edit: { Program_Name: 'Sample Sheet', TableUserColumn: 'Technical_Sheet_Maker', TableUpdaterColumn: 'Technical_Sheet_Updater', TableUpdateColumn: 'Technical_Sheet_Update', Table_Name: 'Product', TableIDColumn: 'Product_No' } , 
   Sample_Sheet_Preview: { Program_Name: 'Sample Sheet', TableUserColumn: 'Technical_Sheet_Maker', TableUpdaterColumn: 'Technical_Sheet_Updater', TableUpdateColumn: 'Technical_Sheet_Update', Table_Name: 'Product', TableIDColumn: 'Product_No' } , 
   Style_Size_Match: { Program_Name: 'Style Size Match', TableUserColumn: 'UserID', TableUpdaterColumn: 'Size_Match_Updater', TableUpdateColumn: 'Size_Match_Update', Table_Name: 'Style', TableIDColumn: 'Style_No' } , 
   Sample_Production: { Program_Name: 'Sample Order', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Samples', TableIDColumn: 'ProduceID' } , 
   Style: { Program_Name: 'Style', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Style', TableIDColumn: 'Style_No' } , 
   Product_Edit: { Program_Name: 'Product', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Product', TableIDColumn: 'Product_No' } , 
   Product_Structure: { Program_Name: 'Product Structure', TableUserColumn: 'Structure_Maker', TableUpdaterColumn: 'Structure_Updater', TableUpdateColumn: 'Structure_Update', Table_Name: 'Product', TableIDColumn: 'Product_No' } , 
   Product_Component_List: { Program_Name: 'Product Component', TableUserColumn: '', TableUpdaterColumn: '', TableUpdateColumn: '', Table_Name: 'Product_Component', TableIDColumn: 'ComponentID' } , 
   Samples: { Program_Name: 'Sample Order', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Samples', TableIDColumn: 'ProduceID' } ,    
   Quotation: { Program_Name: 'Quotation', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Quotation', TableIDColumn: 'Quotation_No' } , 
   Order_Approve: { Program_Name: 'Order Approve', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Order_Approve', TableIDColumn: 'Order_ApproveID' } , 
   Order: { Program_Name: 'Order', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Orders', TableIDColumn: 'Order_No' } ,
   Pre_Production_Sample_Request: { Program_Name: 'Pre_Production_Sample_Request', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Samples', TableIDColumn: 'ProduceID' } ,
   Packing_Order: { Program_Name: 'Packing_Order', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Order_PKO', TableIDColumn: 'Order_PKOID' } ,
   PKO: { Program_Name: 'PKO', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Orders', TableIDColumn: 'Order_No' } ,
   OPI: { Program_Name: 'Order Proforma Invoice', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'OPI', TableIDColumn: 'PI_No' } ,
   PPO: { Program_Name: 'Product Purchase Order', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'PPO', TableIDColumn: 'PO_No' } ,
   Product_Shipment_Edit: { Program_Name: 'Product_Shipment_Edit', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'PDSP', TableIDColumn: 'Shipment_No' } ,
   Sample_Shipment_Edit: { Program_Name: 'Sample_Shipment_Edit', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'SPSP', TableIDColumn: 'Shipment_No' } ,
   Sample_Debit_Note_Edit: { Program_Name: 'Sample_Debit_Note_Edit', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Debit', TableIDColumn: 'Debit_No' } ,
   Model_Edit: { Program_Name: 'Model_Edit', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Model', TableIDColumn: 'Model_No' } ,
   Model_Debit_Edit: { Program_Name: 'Model_Debit_Edit', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Debit', TableIDColumn: 'Debit_No' } ,
   Model_Purchase_Order_Edit: { Program_Name: 'Model_Purchase_Order_Edit', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Model_Order', TableIDColumn: 'Model_Order_No' } ,
   Customer: { Program_Name: 'Customer', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Customer', TableIDColumn: 'CustomerID' } ,
   Supplier: { Program_Name: 'Supplier', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Supplier', TableIDColumn: 'SupplierID' } ,
   Product_In: { Program_Name: 'Product_In', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Product_In', TableIDColumn: 'Product_In_No' } ,
   Product_Out: { Program_Name: 'Product_Out', TableUserColumn: 'UserID', TableUpdaterColumn: 'Data_Updater', TableUpdateColumn: 'Data_Update', Table_Name: 'Product_Out', TableIDColumn: 'Product_Out_No' } ,
   home: { Program_Name: 'Product', TableUserColumn: 'UserID', TableUpdaterColumn: 'Technical_Sheet_Updater', TableUpdateColumn: 'Technical_Sheet_Update', Table_Name: 'Product', TableIDColumn: 'Product_No' } , 
}

var Groups = {
   home:['it admin', 'it author', 'it group'],
   Exchange_Rate:['public', 'it admin', 'it author', 'it group', 'accounting admin', 'accounting Author', 'accounting group'],
   Sample_Sheet_Preview:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc Author', 'qc group'],
   Sample_Sheet_Edit:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Style_Size_Match:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Style_Process:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Component_Photo_Upload:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Component_Photo_Selector:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Product_Structure:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc group'],
   Samples:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Sample_List:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Sample_Shipment_Edit:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Sample_Shipment_List:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Sample_Shipment_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Sample_Debit_Note_List:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Sample_Debit_Note_Edit:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Sample_Debit_Note_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Model_List:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Model_Edit:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Model_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Model_Debit_List:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Model_Debit_Edit:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Model_Debit_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Model_Purchase_Order_List:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Model_Purchase_Order_Edit:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Model_Purchase_Order_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Style:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Style_List:['public', 'it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Composite_Material:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Material_Search:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Product_List:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Product_Structure_Color_Swatch_File:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc Author', 'qc group'],
   Product_Structure_Cutting_Die:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc Author', 'qc group'],
   Product_Structure_Pattern_Grading_Sheet:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc Author', 'qc group'],
   Product_Structure_Pricing:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   Product_Component_List:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group'],
   MPI_List:['public','it admin', 'it author', 'it group', 'store admin', 'stock author', 'store group'],   
   Quotation_List:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],   
   Quotation_CostBreakDown:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],   
   Quotation_Report:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],   
   Quotation:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],  
   Brand_Goal:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Order:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Pre_Production_Sample_Request:['it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Pre_Production_Sample_Tracking_Control:['public','it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Technology_Transfer_Model_Control:['public','it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],   
   Order_Report_Size_Run_Detail:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Order_List:['public', 'it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Order_Approve:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Order_Approve_Report:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Order_Approve_List:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Order_Report_SKU_Detail:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Order_Report_New_Order_Info:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   OPI_List:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   OPI:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   PPO_List:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   PPO:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Customer_List:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Customer:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Product_Shipment_Detail:['public','it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Produce:['public','it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Production_List:['public','it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Production_Progress_Control:['public','it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Production_Material_Deliver_Status:['public','it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc author', 'qc group'],
   Production_Material_Deliver_Status_Detail:['public','it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc author', 'qc group'],
   PreProcessing_Control:['public','it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc author', 'qc group'],   
   Production_Posted:['public','it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Production_Daily_Report_Edit:['public','it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Worksheet_List:['it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Worksheet:['it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Work_Gang_Selector:['it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Production_Generator:['public','it admin', 'it author', 'it group'],
   Shipping_Advice:['accounting admin','accounting author','accounting group','it admin', 'it author', 'it group', 'qc admin', 'sales admin', 'sales author', 'sales group', 'shipping admin', 'shipping author', 'shipping group', 'stock admin'],
   Product_Shipment_Edit:['accounting admin','accounting author','accounting group','it admin', 'it author', 'it group', 'qc admin', 'sales admin', 'sales author', 'sales group', 'shipping admin', 'shipping author', 'shipping group', 'stock admin'],
   Product_Shipment_List:['public','it admin', 'it author', 'it group'],
   Shipping_Status:['accounting admin','accounting author','accounting group','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'shipping admin', 'shipping author', 'shipping group'],
   Shipping_Status_Detail:['accounting admin','accounting author','accounting group','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'shipping admin', 'shipping author', 'shipping group'],
   Supplier_List:['public','it admin', 'it author', 'it group', 'purchase admin', 'purchase author', 'purchase group'],
   Supplier:['public','it admin', 'it author', 'it group', 'accounting admin', 'accounting author', 'accounting group', 'sales admin', 'sales author', 'sales group', 'purchase admin', 'purchase author', 'purchase group'],
   Material_List:['public','it admin', 'it author', 'it group', 'purchase admin', 'purchase author', 'purchase group'],
   Schedule_Edit:['public','it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc author', 'qc group'],
   Production_Status:['public','it admin', 'it author', 'it group', 'develop admin', 'develop author', 'develop group', 'qc admin', 'qc author', 'qc group'],
   Production_Planner:['public','it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Production_Planner_Report:['public','it admin', 'it author', 'it group', 'qc admin', 'qc author', 'qc group'],
   Knowledge_Playlist:['accounting group', 'develop group', 'it group', 'personnel group', 'purchase group', 'qc group', 'sales group', 'shipping group', 'stock group'],
   Knowledge_Detail:['public', 'accounting group', 'develop group', 'it group', 'personnel group', 'purchase group', 'qc group', 'sales group', 'shipping group', 'stock group'],
   Product_In_List:['public','it admin', 'it author', 'it group', 'stock admin', 'stock author', 'stock group'],
   Product_In:['public','it admin', 'it author', 'it group', 'stock admin', 'stock author', 'stock group'],
   Product_Out_List:['public','it admin', 'it author', 'it group', 'stock admin', 'stock author', 'stock group'],
   Product_Out:['public','it admin', 'it author', 'it group', 'stock admin', 'stock author', 'stock group'],   
   Product_Packing:['public','it admin', 'it author', 'it group', 'stock admin', 'stock author', 'stock group'],
   Product_Stock_List:['public','it admin', 'it author', 'it group', 'stock admin', 'stock author', 'stock group'],
   PKO_List:['public', 'it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Packing_Order:['public', 'it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Packing_Order_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Produce_PKO_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   PKO:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Shipment_Packing_List_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group'],
   Packing_List:['public', 'it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Packing_List_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Packing_List_Edit:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Shipment_Plan_List:['public', 'it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Shipment_Plan_Report:['public','it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'],
   Shipment_Plan_Edit:['it admin', 'it author', 'it group', 'sales admin', 'sales author', 'sales group', 'qc admin', 'qc author', 'qc group'], 
}

const Permission = {
  SharePG: Share_Prog,
  Groups: Groups,
}

module.exports = Permission;